import unittest

from face_finder.web_server import PAGE, GENERAL_ARCHIVE, archive_path_for_name


class WebGalleryUiTests(unittest.TestCase):
    def test_gallery_uses_timeline_and_automatic_metadata_saving(self) -> None:
        self.assertIn('.panel{width:100vw;max-width:none;height:100vh', PAGE)
        self.assertIn('grid-template-columns:minmax(0,1fr) clamp(340px,25vw,460px)', PAGE)
        self.assertIn('.viewer img{max-width:100%;max-height:100vh}', PAGE)
        self.assertIn('id=timeline class=timeline', PAGE)
        self.assertIn('className=\'year-group\'', PAGE)
        self.assertIn('setTimeout(save,immediate?0:700)', PAGE)
        self.assertIn('Saved automatically', PAGE)
        self.assertIn('id=map class=map', PAGE)
        self.assertIn('Open in OpenStreetMap', PAGE)
        self.assertIn("'locationName','latitude','longitude'", PAGE)
        self.assertIn('Model detections', PAGE)
        self.assertIn('automatic NSFW decision', PAGE)
        self.assertIn('explicit-content evidence', PAGE)
        self.assertIn('NSFW conflicts', PAGE)
        self.assertIn('Models disagree', PAGE)
        self.assertIn('Danger: permanently delete photo?', PAGE)
        self.assertIn('This action cannot be undone.', PAGE)
        self.assertIn("post('/api/delete-photo'", PAGE)
        self.assertIn("new IntersectionObserver", PAGE)
        self.assertIn("rootMargin:'600px 0px'", PAGE)
        self.assertIn("if(loading){if(reset)reloadAfterLoad=true;return}", PAGE)
        self.assertIn("function timelineGrid(photo)", PAGE)
        self.assertIn("className='month-group'", PAGE)
        self.assertIn("className='day-group'", PAGE)
        self.assertIn("weekday:'long',month:'long',day:'numeric'", PAGE)
        self.assertIn("c.dataset.photoId=x.id", PAGE)
        self.assertIn("removeDeletedCard(deletedId)", PAGE)
        self.assertIn("offset = Math.max(0, offset - 1)", PAGE)
        self.assertIn("deleteScrollPosition = window.scrollY", PAGE)
        self.assertIn("requestAnimationFrame(() => window.scrollTo", PAGE)
        self.assertIn("Select photos", PAGE)
        self.assertIn("Archive selected", PAGE)
        self.assertIn("Delete selected", PAGE)
        self.assertIn("Mark safe", PAGE)
        self.assertIn("Mark NSFW", PAGE)
        self.assertIn("post('/api/nsfw-override'", PAGE)
        self.assertIn("const selectedPhotos = new Map()", PAGE)
        self.assertIn("'/api/archive-photos' : '/api/delete-photos'", PAGE)
        self.assertIn("Existing archive", PAGE)
        self.assertIn("Or create a new archive", PAGE)
        self.assertIn("payload.archive_name", PAGE)
        self.assertIn('>Timeline</button>', PAGE)
        self.assertIn('>Identity</button>', PAGE)
        self.assertIn('Identity management', PAGE)
        self.assertIn('<th>ID</th>', PAGE)
        self.assertIn('New identity', PAGE)
        self.assertIn('Merge selected', PAGE)
        self.assertIn('Date last seen', PAGE)
        self.assertIn('Number of photos', PAGE)
        self.assertIn('id=identitySort', PAGE)
        self.assertIn("identitySort.value === 'name'", PAGE)
        self.assertIn("identitySort.value === 'photo_count'", PAGE)
        self.assertIn("right.last_seen||''", PAGE)
        self.assertIn('<th>Last seen</th>', PAGE)
        self.assertIn('requestIdentityMerge', PAGE)
        self.assertIn("post('/api/merge-identities'", PAGE)
        self.assertIn('The removed identity IDs cannot be restored.', PAGE)
        self.assertIn('(#${p.id})', PAGE)
        self.assertIn('Recognized people', PAGE)
        self.assertIn('Unidentified people', PAGE)
        self.assertIn('Similar unidentified people', PAGE)
        self.assertIn('Add to known identity', PAGE)
        self.assertIn('assignUnknownCluster', PAGE)
        self.assertIn("post('/api/assign-unknown-groups'", PAGE)
        self.assertIn("group.group_ids", PAGE)
        self.assertIn('const sortedGroups', PAGE)
        self.assertIn("right.photo_count-left.photo_count", PAGE)
        self.assertIn("right.last_seen||''", PAGE)
        self.assertIn('<th>Anonymous group</th><th>Last seen</th>', PAGE)
        self.assertIn("api('/api/unidentified-summaries')", PAGE)
        self.assertIn('/api/unidentified-reference?id=', PAGE)
        self.assertIn('viewUnidentifiedTimeline', PAGE)
        self.assertIn('unknown_group_id:unknownGroupFilter', PAGE)
        self.assertIn('id=identityTableBody', PAGE)
        self.assertIn("api('/api/identity-summaries')", PAGE)
        self.assertIn('item.has_library_photos', PAGE)
        self.assertIn('await people(true);', PAGE)
        self.assertIn("post('/api/identity'", PAGE)
        self.assertIn("nameInput.addEventListener('input'", PAGE)
        self.assertIn('setTimeout(saveIdentityName, 700)', PAGE)
        self.assertIn('Name changed — saving...', PAGE)
        self.assertIn('View photos', PAGE)
        self.assertIn('Reference images', PAGE)
        self.assertIn("identity.reference_face_ids", PAGE)
        self.assertIn('/api/identity-reference?id=', PAGE)
        self.assertIn('openReferencePreview', PAGE)
        self.assertIn('reference-not-face', PAGE)
        self.assertIn('removeCurrentReferenceFace', PAGE)
        self.assertIn('referenceDialog.dataset.faceId', PAGE)
        self.assertNotIn('referenceItem.append(previewButton, removeButton)', PAGE)
        self.assertNotIn('referenceItem.append(button, removeButton)', PAGE)
        self.assertIn('removeReferenceFace', PAGE)
        self.assertIn('False reference face removed', PAGE)
        self.assertIn('removed from the catalog and biometric matching', PAGE)
        self.assertIn('Not a face / remove', PAGE)
        self.assertIn('Show tags', PAGE)
        self.assertIn('toggleFaceTags', PAGE)
        self.assertIn('id=albumFilter', PAGE)
        self.assertIn("api('/api/albums')", PAGE)
        self.assertIn("api('/api/album-suggestions')", PAGE)
        self.assertIn("post('/api/photo-albums'", PAGE)
        self.assertIn('suggested albums</summary>', PAGE)
        self.assertIn('New album…', PAGE)
        self.assertIn('.app-tabs{position:sticky;top:0;z-index:4', PAGE)
        self.assertIn('function closePhotoViewer()', PAGE)
        self.assertIn("if (modal.style.display === 'block') closePhotoViewer()", PAGE)
        self.assertIn('focusFaceAssignment', PAGE)
        self.assertIn('activateFaceReticle', PAGE)
        self.assertIn('activeFaceReticleId', PAGE)
        self.assertIn('face-reticle.active', PAGE)
        self.assertIn('Unknown person ${number}', PAGE)
        self.assertIn('input.scrollIntoView', PAGE)
        self.assertIn("'face-reticle ' +", PAGE)
        self.assertIn("face.unknown ? 'unknown' : 'unprocessed'", PAGE)
        self.assertIn('full.naturalWidth', PAGE)
        self.assertIn('Manual person tags', PAGE)
        self.assertIn("post('/api/photo-identity-tag'", PAGE)
        self.assertIn('Target on photo', PAGE)
        self.assertIn('pendingManualTagIdentityId', PAGE)
        self.assertIn("full.addEventListener('click'", PAGE)
        self.assertIn('target_x:targetX,target_y:targetY', PAGE)
        self.assertIn('face-reticle manual-tag', PAGE)
        self.assertIn('Auto-detect cats and dogs', PAGE)
        self.assertIn("post('/api/detect-pets'", PAGE)
        self.assertIn("post('/api/pet-tag'", PAGE)
        self.assertIn('face-reticle pet', PAGE)
        self.assertIn('Pet targeting cancelled', PAGE)
        self.assertIn('Manual tag targeting cancelled', PAGE)
        self.assertIn('assignment_suggestions', PAGE)
        self.assertIn('Type or choose an identity', PAGE)
        self.assertIn('Same day · ', PAGE)
        self.assertIn('% match', PAGE)
        self.assertIn('assignFaceFromInput', PAGE)
        self.assertIn("post('/api/create-identity'", PAGE)
        self.assertNotIn("current = null;\n    await load();", PAGE)
        self.assertNotIn('>Save metadata</button>', PAGE)

    def test_archive_destination_defaults_and_rejects_paths(self) -> None:
        self.assertEqual(archive_path_for_name(), GENERAL_ARCHIVE)
        self.assertEqual(archive_path_for_name("Trips"), GENERAL_ARCHIVE.parent / "Trips.zip")
        self.assertEqual(
            archive_path_for_name("Existing.hide"), GENERAL_ARCHIVE.parent / "Existing.hide"
        )
        with self.assertRaises(ValueError):
            archive_path_for_name("../outside.zip")
        with self.assertRaises(ValueError):
            archive_path_for_name("bad.exe")


if __name__ == "__main__":
    unittest.main()
